#include "UITreeIcon.h"
const char* ICON_TAG_PARENT[] = {
	"11 11 2 1",
	"o c #121212",
	"a c #EE0000",
	"oooooaooooo",
	"oooooaooooo",
	"oooooaooooo",
	"oooooaooooo",
	"oooooaooooo",
	"aaaaaaaaaaa",
	"oooooaooooo",
	"oooooaooooo",
	"oooooaooooo",
	"oooooaooooo",
	"oooooaooooo"};
const char* ICON_TAG_CHILD[] = {
	"11 11 2 1",
	"o c #121212",
	"a c #98FB98",
	"aoooooooooa",
	"oaoooooooao",
	"ooaoooooaoo",
	"oooaoooaooo",
	"ooooaoaoooo",
	"oooooaooooo",
	"ooooaoaoooo",
	"oooaoooaooo",
	"ooaoooooaoo",
	"oaoooooooao",
	"aoooooooooa"};
const char* ICON_TAG_SELECTED[] = {
	"11 11 3 1",
	"o c #9B30FF",
	"a c #98FB98",
	"b c #00FFFF",
	"bbbbbbbbbbb",
	"aaoooboooaa",
	"aoaoobooaoa",
	"aooaoboaooa",
	"aoooabaoooa",
	"bbbbbabbbbb",
	"aoooabaoooa",
	"aooaoboaooa",
	"aoaoobooaoa",
	"aaoooboooaa",
	"bbbbbbbbbbb"};
const char* ICON_TAG_OPEN_PIXMAP[] = {
	"11 11 2 1",
	".  c None",
	"@  c #000000",
	"...@.......",
	"...@@......",
	"...@@@.....",
	"...@@@@....",
	"...@@@@@...",
	"...@@@@@@..",
	"...@@@@@...",
	"...@@@@....",
	"...@@@.....",
	"...@@......",
	"...@......."};
const char* ICON_TAG_CLOSE_PIXMAP[] = {
	"11 11 2 1",
	".  c None",
	"@  c #000000",
	"...........",
	"...........",
	"...........",
	"...........",
	"...........",
	"@@@@@@@@@@@",
	".@@@@@@@@@.",
	"..@@@@@@@..",
	"...@@@@@...",
	"....@@@....",
	".....@....."};
const char* ICON_WINDOW[] = {
/* columns rows colors chars-per-pixel */
"128 128 160 2 ",
"   c #818267672424",
".  c #85E46AFB25DB",
"X  c #8B0D6F13270B",
"o  c #89DF6EC428D3",
"O  c #8CB4708E2727",
"+  c #8E5671D82898",
"@  c #92F6756A299D",
"#  c #971278E42AE3",
"$  c #9C967D1D2C93",
"%  c #939377773131",
"&  c #959579CF3232",
"*  c #9A857D7D335E",
"=  c #A0A07F7F2D2D",
"-  c #9F9F80802E2E",
";  c #9D9D80803535",
":  c #9D9D818139BA",
">  c #A42E833C2EE1",
",  c #A8A886862F2F",
"<  c #A6B7859030D6",
"1  c #A98587653032",
"2  c #AD878AC931E3",
"3  c #A14B84DA3AE5",
"4  c #A7A789893E3E",
"5  c #ACAC8C673AA8",
"6  c #B2A48EC63307",
"7  c #B1318F8F3A3A",
"8  c #B64191C7343F",
"9  c #BAAC953D35AC",
"0  c #BF0E98DF36D6",
"q  c #B5E8932C3B08",
"w  c #BA20962F3B08",
"e  c #BE3E99993CBD",
"r  c #C12A9A303737",
"t  c #C4789CF238BC",
"y  c #C8C89F9F3943",
"u  c #CD05A33A3ACE",
"i  c #D21BA7343C11",
"p  c #D5D3AA473D7F",
"a  c #DB04AE663EC6",
"s  c #DDEBB0BE3F3F",
"d  c #A6A68A8A4545",
"f  c #AA2A8C8C41C2",
"g  c #B4B494544282",
"h  c #B8B897414242",
"j  c #BC899A004411",
"k  c #B2B2953F4BA1",
"l  c #BEBE9D9D4ACB",
"z  c #BBBB9F1F5656",
"x  c #C3439EC94343",
"c  c #C0C09E9E4B4B",
"v  c #C69BA1214242",
"b  c #CB64A4BE43C4",
"n  c #C5C5A33C4BB2",
"m  c #CB4BA7274BCC",
"M  c #CBCBA8A84E4E",
"N  c #D386AAF74545",
"B  c #DA2FAEAE4343",
"V  c #D3D3AD2D4DCE",
"C  c #DF4EB1DD407A",
"Z  c #D6D6B0B04F4F",
"A  c #DB74B2184BB2",
"S  c #C46EA34D5151",
"D  c #CD9AABAB54EE",
"F  c #C3C3A5A55BDC",
"G  c #CE4EADAD59DA",
"H  c #D0D0AFAF5C5C",
"J  c #D5D5B2075656",
"K  c #DCDCB55F51A7",
"L  c #D4D4B3195CF6",
"P  c #DADAB7375BDC",
"I  c #E309B4D44154",
"U  c #E7CDB8C5429C",
"Y  c #EC7BBC464441",
"T  c #E3E3B7B74848",
"R  c #E666B9B94AA0",
"E  c #ECB9BE574A4A",
"W  c #F104BFBF4545",
"Q  c #E645BCBC54D4",
"!  c #E9B6BEF153ED",
"~  c #E3B0BD235CC3",
"^  c #C7C7AAAA6060",
"/  c #C4C4AC6C6B2B",
"(  c #CA4AAF2F6B6B",
")  c #CFCFB0B06464",
"_  c #D3D3B4096464",
"`  c #DC3BBA196343",
"'  c #DCDCBCBC6C16",
"]  c #CDCDB4B473F4",
"[  c #D453B9B974F5",
"{  c #D353BABA7ABA",
"}  c #D959BF3F7BFC",
"|  c #E2A2BE3E62A2",
" . c #EF2EC1004D0D",
".. c #F4C7C30D46B7",
"X. c #F8FDC6C64747",
"o. c #F5DBC52B4ACB",
"O. c #F976C7774904",
"+. c #FAECC93A49EF",
"@. c #EE43C2C25656",
"#. c #EB21C2D45D38",
"$. c #F3F3C71C55AB",
"%. c #F7A1C9C955AB",
"&. c #FAEACBD553F1",
"*. c #F2B2C7065999",
"=. c #F4F4C9C95C9C",
"-. c #FAEECEA75DE6",
";. c #E58FC16B6610",
":. c #EC7AC5A86380",
">. c #E4E4C3186CC2",
",. c #EB40C71C6BC1",
"<. c #EEEEC94968E9",
"1. c #F0F0C7C7610B",
"2. c #F39DCB2064BA",
"3. c #FAF5CF9F6186",
"4. c #F486CDF26CFF",
"5. c #FBCFD17765DF",
"6. c #F7F7D0D06D6D",
"7. c #FBF9D3496C69",
"8. c #E455C3E072E4",
"9. c #E93EC771751F",
"0. c #EDEDCCCC7777",
"q. c #E463C6467CFD",
"w. c #E7E7C9C97C7C",
"e. c #ECECCC8C7BBB",
"r. c #F247CECE731D",
"t. c #F0F0CFCF7E7E",
"y. c #F4F4D0D07676",
"u. c #FBF0D5B4739F",
"i. c #F554D3327BDB",
"p. c #FBF8D72279E8",
"a. c #FBFBD8F67DEF",
"s. c #DEDEC5C58484",
"d. c #E3E3C7C78080",
"f. c #EC96CECE83D9",
"g. c #E5E5CCCC8E8E",
"h. c #EBEBCFCF8A8A",
"j. c #F489D46983C3",
"k. c #F9F9D7D78181",
"l. c #FBFADA6F8457",
"z. c #F2F2D52A8A8A",
"x. c #F6F6D8D88C36",
"c. c #FC99DC8E8C7E",
"v. c #EB6BD2D29494",
"b. c #EEEED7D79C1C",
"n. c #EEEED8D89E9E",
"m. c #F676DADA9413",
"M. c #FCF6DF17945A",
"N. c #F4F4DC9C9E1E",
"B. c #FB3ADF5F9959",
"V. c #FCFCE0E09797",
"C. c #FCEAE1AA9C09",
"Z. c #EF6EDA04A0F6",
"A. c #F373DD5DA524",
"S. c #F8F8DFDFA1A1",
"D. c #FCF3E408A45E",
"F. c #F6F6E0E0A8A8",
"G. c #FCF5E695AC87",
"H. c #FCFCE7E7B0B0",
"J. c #FCFCE8E8B27D",
"K. c None",
/* pixels */
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.I I I I I I I I I I I I I I I I I I I I I I I I I I I I I C I I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I I I I I I C I I I I C I I I I I I I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I I I I I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I C I I I I C I I I I I I I I I I I I I I I I I I I I I I I I I I I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.C I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I C I I I C I I I I C I I I I I I C I I I I I I I I I I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I I I I I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.s I I I I I I I I I I I I I I I I I I I I I I C I I I C I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I I I I C I I I I I C I I I I C K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.y I I I I I I I I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I C I I I I I I C I I I I I I I I I I I I I I I I I C I I I I I I C I I I I I I I I I I I I I I K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.r I I I I I C I I I I I I I I C I I I I C I I I I I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I I I I I I I I U p K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.# p I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I W I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.. # u I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I I I U C I I U E W U I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.    . 2 u C I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I C I I I I I I I C I I I I I C I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I U C U E o.&.W W Y I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.        o - 0 p I I I I I I I I I I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I C U U  .*.%.+.+.W W W U I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.              o # 8 u p I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I C I I I I I C I I I I I I I I C U T ! @.1.5.5.-.3.&.+.O.X.X.W U C p K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.                    . O # 2 0 u s I I I I I I I I I I I I I I I I I I C I I I I I I I I C I I I I I I I I I I I I C I I I I I I I I I I I I I I I I I I I R ! #.2.6.y.u.u.7.7.5.5.-.3.&.+.+...W W U I i K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . @ > 2 0 y i B C I I I I I I I I I I I I I C C I I I I I I I C I I I I I C I I I I I I I I I I I I R R ! ! #.:.4.i.k.c.M.c.c.c.l.k.a.p.u.u.7.5.5.-.3.&.+.+.X...W Y C p K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                  . . . . o X + $ = > 2 q e x b N Z Z Q Q #.@.#.#.:.#.@.@.Q @.Q Q @.Q :.:.:.#.:.1.1.<.<.4.4.i.i.k.k.x.c.M.M.B.B.B.M.M.M.M.c.c.c.l.l.a.p.u.7.7.5.5.-.3.&.+.+...W W Y C i K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                o . . . O X X + + @ @ # # $ # $ = - > > , 2 2 2 8 8 0 0 v v b N N p B B T I U E ..O.3.6.u.p.l.l.c.c.c.M.M.M.M.B.M.M.M.M.M.c.c.l.l.a.p.u.7.7.5.5.-.-.&.O.O.X.W W U I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . O O O O + O @ @ # $ # $ > - < < < 1 2 2 8 8 8 8 0 0 0 t u u p p s I I W W O.-.7.u.p.a.l.l.c.c.M.M.V.M.B.V.M.M.M.c.c.c.l.l.a.p.u.7.7.7.3.-.-.&.+.+.X...W U s i K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . O O X O O @ @ # # $ # $ $ - > > 1 1 1 2 2 6 8 8 0 0 t t t u p p a I U Y ..X.-.7.u.p.a.l.l.c.M.c.M.M.V.V.M.B.M.M.M.c.c.l.l.a.p.u.u.7.5.3.-.-.-.+.+.....W U I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . X   X . O O @ @ @ # # # $ $ > - > > < 1 2 2 8 8 8 8 0 0 t t u u p p s I U Y ..X.-.5.u.p.a.l.c.c.c.M.M.V.M.B.V.M.M.M.c.c.c.l.l.a.p.u.7.7.5.5.-.-.&.+.+.X...Y U s p K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . . . . . O O O O @ O @ # # # # $ $ > > > < 1 1 2 2 8 8 8 8 0 0 t u u p p s I I Y ..X.-.7.u.p.a.l.l.c.c.M.M.M.V.M.M.M.M.M.M.c.c.l.l.a.p.u.7.7.7.3.-.-.&.+.+.....W U s i K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . X . . . O O O O @ @ @ # # $ $ - > > > , 1 1 2 8 8 8 8 0 0 r y y u p p C I I Y W X.-.7.u.p.a.l.c.c.c.c.M.M.M.M.V.V.M.M.c.c.c.l.l.a.p.u.u.7.5.3.-.3.&.O.+.......U I i K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . O X O O @ @ @ @ # $ # $ $ - > > > 1 2 2 2 6 8 8 0 0 0 y u u i p s I U Y ..O.&.7.7.p.a.l.l.c.M.M.M.M.M.M.V.M.M.M.c.c.c.l.l.a.p.u.7.7.5.3.-.3.&.O.O.....W U s p K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . X X O O @ + @ # # # $ $ - - > < < 1 2 2 8 6 8 8 0 0 t t u i i p s I U W ..X.&.7.u.u.k.l.c.c.M.M.M.B.V.M.B.M.M.M.M.c.c.l.l.a.p.u.7.7.5.5.-.-.&.O.X.....W U C i K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . . X X O + @ + # @ $ # $ - - > > < 1 2 2 2 8 8 8 0 0 r t u u p p s C I W W X.-.7.u.p.a.l.l.c.c.c.M.M.B.M.V.V.M.M.c.c.c.l.l.a.p.p.7.7.5.5.-.3.&.O.X.....W U s K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                  . X . X X X O @ + @ # @ $ $ $ = > > > > , 1 2 6 8 8 8 9 0 t t t u p p s s U U ..+.-.5.u.a.a.l.l.c.c.c.M.M.V.V.M.M.M.M.M.c.c.l.a.a.p.u.7.7.5.5.-.-.-.+.+.....W U s K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . . O X O + + @ # @ # $ $ $ = > > > 1 2 2 8 6 8 9 9 0 t t u u i p s s s ....X.-.5.u.p.a.l.c.c.c.M.M.V.B.M.V.M.M.c.c.c.c.l.l.a.p.p.7.7.5.5.-.-.&.+.+.....Y Y s K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . X X X + + @ @ @ # # $ $ $ - > > > 1 2 2 2 6 8 8 9 0 r y y u i p s I U U ..X.-.5.u.p.a.l.l.c.M.M.M.M.M.V.M.B.M.c.M.c.c.c.l.p.p.u.7.7.5.5.-.-.&.+.X.....W U I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                  X . . . O X O @ + @ # @ # # $ = > > > < 1 1 2 6 6 8 9 9 0 r t y u p p s s U U ..X.-.5.u.p.a.l.l.c.c.M.M.M.V.B.M.M.M.M.M.c.c.l.k.a.p.u.7.7.5.5.-.-.&.X.+.....Y U C K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . X O O X + @ + # @ # $ $ = $ > > , 1 1 2 6 6 8 9 9 0 r r u u p p B I U ....X.&.5.u.p.a.l.c.c.c.M.M.V.M.B.V.B.M.M.c.c.c.l.l.a.p.u.u.5.5.5.-.-.&.+.+...W W U C K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                  . . . . X O + + + @ @ # # $ # = $ > > > 1 2 2 2 6 8 8 9 0 r y y u i p a s U U ..X.-.5.u.p.a.a.l.c.M.c.M.M.V.V.M.V.M.M.M.c.c.l.l.p.p.u.7.7.5.5.-.-.&.+.+.....Y U I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . X . X X X X @ @ + # @ # # $ = > > < , 1 2 6 2 8 8 8 9 0 r y y u i p s s U U ..X.-.5.u.p.a.l.l.c.c.M.M.V.M.B.V.M.M.M.c.c.c.l.a.a.p.u.7.7.5.5.-.-.&.X.O.....Y U a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . . O X O + + @ # # # $ $ $ $ > > , 1 1 2 2 6 8 9 9 0 r y y u p p a s U Y ..X.-.5.u.a.a.l.l.c.M.c.M.M.M.V.M.V.M.M.c.c.c.l.l.a.p.u.7.7.5.5.-.-.&.+.O.....W U I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . X . . X X X @ @ + @ # # $ $ = $ > > , , 1 6 2 6 8 9 9 0 0 t y u p p a I U Y ..X.-.5.u.p.a.l.c.c.c.M.M.M.M.M.V.V.M.M.M.c.c.l.l.a.p.u.7.7.5.3.-.-.&.+.+.....W U C K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                  . . . . X X X + + @ # @ # $ $ $ $ > > > 1 1 2 2 6 8 8 9 0 0 y y u i p a C U U ..O.-.7.7.p.a.k.l.c.M.c.M.M.M.M.B.M.M.M.c.c.c.l.l.a.p.p.7.7.5.5.-.-.&.O.+...W Y U C K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . X + X X + @ + # # # $ $ $ > > > > 1 1 6 2 8 6 9 9 0 t t y u p p a a U Y ..O.&.7.7.p.a.k.c.c.M.c.M.M.V.V.M.M.M.M.M.c.c.l.l.p.p.u.7.7.5.5.-.-.&.+.O.....W U p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . X X X @ + @ @ # # # $ = $ > > < 1 1 2 6 6 8 8 w 0 0 y y u i p B s U Y Y O.&.5.u.p.a.k.l.c.c.M.M.V.M.B.V.M.M.M.c.c.c.l.l.a.p.p.7.7.5.5.-.-.&.+.O.....Y p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K..                           . . . . . X X X + + + # @ # # $ = $ > > > 1 1 2 2 6 8 8 9 0 0 y y u p p a C U Y ..O.&.7.u.p.a.l.c.c.M.M.M.M.M.V.B.B.M.M.M.c.c.l.a.a.p.u.7.7.7.3.-.-.&.O.O.X.U a I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K., .                           X . . . O X X + @ + # # # $ $ $ $ > < > 1 1 6 6 8 6 9 9 0 0 t y u p p a C U U ..O.&.7.7.p.a.l.l.c.c.c.M.V.M.M.V.M.M.M.c.c.c.l.l.p.p.u.7.7.5.3.-.-.&.O.o.B I ..Y I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.r t r #                         . . . X X X O + + @ # @ # $ # = - > > < 1 1 2 2 6 6 8 9 0 t t y u i p a a U Y ..+.&.7.7.p.a.l.l.c.c.c.M.M.V.V.M.M.M.M.c.c.c.c.l.a.p.u.u.7.5.3.-.-. .N t ..O.X...W K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.t y y y 2 .                   . . . . . O X O + @ + # @ # $ # = $ > > < 1 2 2 2 8 8 9 9 0 r y y u i p a s I U ..O.&.5.7.p.a.l.c.c.c.M.M.M.M.V.B.M.M.M.M.c.c.l.k.a.p.u.7.7.5.=.A t 6 N =.&.&.O.X.o.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.y y u u u t #                   . X . . X X X + + @ # # # # # = = = > < 1 2 2 6 6 8 8 8 r r t y u i p B C U U ....&.5.u.p.a.a.l.c.c.M.M.M.M.M.B.M.M.M.M.c.x.l.l.p.p.r.:.Z e 2 2 t @.-.-.-.-.&.O...K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.t u u u u i i 6 +               . . . . X X + + @ + # @ # $ $ $ = = > > 1 1 2 2 6 8 9 9 0 r t y u i p p s U E ..X.&.5.u.p.a.l.l.c.M.c.M.M.B.B.M.B.M.M.c.c.c.i.,.J x q 1 1 2 v ! 3.3.-.-.-.-.-.&.I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.2 u u u i i i i u 9 @ .         . . . . X X X + + @ @ @ # $ # = = > > > 1 1 2 2 6 8 9 9 0 r t y u i p s s U U ....&.7.u.p.a.l.c.x.c.M.M.M.M.M.M.x.j.8.L M q 2 1 1 1 2 t A *.-.-.-.-.-.-.-.-.&. .s K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.. 9 u i i i i i p p p y 6 @ .           . . . X X + @ @ # # $ $ = = > > 1 1 2 6 6 6 8 9 0 r t y u i p a B U U ..X.&.5.7.p.a.k.l.k.t.9.>.` G l g 2 , , 1 1 1 1 8 b K 1.3.-.-.-.-.-.3.3.-.3.&.X.U a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.  . 2 i i i i i a p p a a a i r , @ X                 . . X + @ @ # # # = > 1 1 2 2 6 8 8 0 0 t t t y i u i i i p b b v x q 7 2 4 > > < > > > > > 1 6 w M P <.6.6.5.7.5.3.-.-.3.-.-.-.-.&...Y U s K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.    . $ t i i a p p a a a C C I U U C i r 2 = + .       . . . . . . o . X X X o O + + @ @ + @ @ # # # # # # # $ $ $ $ $ - - - - $ = > > 2 g c D ` ,.y.p.u.u.u.7.7.7.5.5.5.-.-.-.-.-.&.o...W W I a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.        . = y i p a a a C C I I U U Y W W W W %.:.~ D S k f * & @ + o o X o X X X X + + + @ + @ # # @ # # @ $ ; * - - 3 4 g z S ) ' q.j.x.x.c.l.l.k.a.p.p.u.u.6.7.7.5.7.5.5.-.-.3.&.+.O...W Y U s K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.            . # 6 u C a C I I U U Y W W O.O.&.3.5.7.u.p.a.l.l.c.x.h.h.d.d.} } [ ] ] ] ( / / / / ] { { ] } s.s.g.v.v.N.S.D.D.D.C.V.M.M.M.c.c.c.l.l.l.k.a.p.p.u.u.u.7.7.5.5.7.3.-.-.&.O.O.X.W Y U a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                  . # 2 u a I U U Y W W W O.-.5.7.u.p.p.k.l.c.c.M.M.B.B.C.D.D.D.G.G.H.H.J.J.J.J.J.J.J.J.H.H.H.G.G.G.G.D.D.D.C.C.C.V.V.M.M.c.c.c.l.l.a.p.p.p.p.u.u.u.u.7.7.5.3.3.-.&.+.X.X...Y U C K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                      .   O = 8 u I W W O.&.3.5.7.u.p.a.k.l.c.c.M.M.V.C.C.D.D.D.D.H.G.H.J.J.J.J.J.J.J.J.H.H.G.H.G.G.G.D.D.D.D.D.C.C.B.V.M.c.c.c.c.l.l.l.l.l.k.a.a.p.u.7.7.5.3.-.-.&.X.X...W W I a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . + # 1 9 N Q 2.6.u.p.k.l.c.c.c.M.M.V.D.D.D.D.D.G.G.H.H.J.J.J.H.J.J.J.J.H.H.G.G.G.G.G.G.D.D.D.C.C.V.V.V.M.V.M.M.M.M.M.M.c.c.l.l.a.p.u.u.7.7.3.-.-.&.O.X.....Y U a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . X . . X X X + & < q c D P ' 9.e.j.x.M.C.D.D.D.D.G.G.H.J.J.J.H.J.J.J.J.H.H.G.G.D.D.C.C.C.V.V.B.M.V.M.V.B.M.B.V.M.M.M.c.c.c.l.l.p.p.u.7.7.5.3.3.-.&.X.X.X.W Y U C K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . X X X + @ + @ # # # $ = > < 5 7 h j x n D D J L P ` ` | | ;.#.#.#.#.*.*.&.-.7.u.p.a.k.l.c.c.M.M.V.M.B.V.V.M.M.M.c.c.l.l.a.p.u.u.7.5.3.-.-.&.+.X...W W U p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . X X X X + @ @ # $ # # $ = $ > > , , 2 2 6 8 9 8 0 0 t y u u p p C I U ..O.&.3.u.p.a.l.l.c.M.c.V.M.M.V.M.B.M.M.c.c.c.l.l.p.p.u.7.7.5.3.-.-.&.+.X...W W I a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . X X X + @ + @ @ @ $ $ $ = > > > , 1 2 2 6 6 8 9 9 0 t y u u p p s U U ..X.&.5.7.p.a.k.c.c.c.M.M.V.M.M.V.M.M.M.c.c.c.l.l.a.p.u.7.7.5.5.-.-.&.+.X.....W I a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . . X X X + @ @ @ @ # # = = $ > > 1 1 2 2 6 6 8 9 0 0 t y u i p p s s U ....&.5.7.p.a.k.l.c.c.c.M.M.V.M.V.M.M.M.M.c.c.l.l.a.p.u.7.7.5.5.-.-.&.+.X...W Y U a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . X X X + @ O @ # # # $ # $ > < > 1 1 2 2 6 6 8 9 0 r t y u i p p s U U ....+.5.u.u.a.a.l.c.c.V.M.V.M.V.M.V.M.M.M.c.c.l.l.a.p.u.7.7.5.3.-.-.&.X.X.X...Y I a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . o . o X X X @ O @ # # # $ $ > $ > > 1 1 2 2 2 8 8 8 9 0 t y u u p a s I U ....&.5.u.p.a.k.l.c.c.c.V.V.M.M.V.M.M.M.c.c.c.l.l.a.p.u.u.7.5.3.3.-.&.X.X.....Y U a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . . O X + O @ @ # # # $ $ $ $ > > , 1 2 2 6 8 8 9 0 0 t y u i p p s I U Y ..&.3.7.p.a.l.l.c.c.c.M.M.V.M.M.M.M.M.M.c.c.l.l.a.p.u.7.7.5.3.-.-.&.+.X...W Y U p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . . . . . O X X O @ @ # # # # $ $ > > < , 1 2 2 2 6 8 9 9 0 r y t i p a s I Y ....&.3.7.u.a.k.c.c.c.M.M.V.M.V.M.M.M.M.c.c.c.l.l.a.p.u.7.7.7.3.-.-.&.X.X.....Y I a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . . . . . O O X + @ @ # # # # $ = $ > > < , 2 2 6 6 8 9 9 0 r y u i p a s I U Y X.&.5.7.p.a.a.l.c.c.M.M.V.M.B.V.B.M.M.c.c.c.l.l.p.p.p.7.7.7.-.-.-.&.O.X.....Y I a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . O O X + + @ # # # $ $ $ > > > < 1 1 2 6 8 8 8 0 r t y u u i a s I U ..X.&.5.7.u.a.l.l.c.c.c.M.M.V.M.M.M.M.M.M.c.c.l.a.a.p.u.7.5.5.3.-.-.+.+.X.....Y U p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . . . . . O O X @ @ @ @ # # # $ - $ > > , 1 2 2 2 6 8 9 9 0 r y u u p a s I Y Y ..+.3.7.u.a.l.l.c.c.M.M.V.M.M.V.V.M.M.c.c.c.l.l.a.p.u.7.7.5.3.-.-.&.X.X...W Y I a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . . . . . O o O O O @ # # # $ $ - = > > , , 2 2 6 6 8 9 0 r t y u u i a s I U ..X.&.5.7.p.a.l.l.c.M.c.M.M.V.M.V.M.M.M.M.c.c.l.l.a.p.u.7.7.7.3.-.-.&.+.X.....Y U p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . . . o . + X X @ @ O # # # # $ = = > > , , 2 1 6 6 8 8 r r t y y i i a s I U E ..+.5.7.u.p.k.l.c.c.M.M.M.V.V.B.M.M.M.M.c.c.l.a.a.p.u.7.7.5.3.-.-.&.+.X.....Y I a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . . . . . X X + O @ @ # @ # $ $ $ = > > , , 2 2 6 6 8 9 9 r r y u i i p s I U W ..&.3.u.a.a.k.l.c.c.c.M.M.V.M.M.M.M.M.c.c.c.l.l.p.p.p.7.7.5.3.-.-.&.O.X...W Y I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . o X X + O @ O # # # # # - = - > , 2 2 2 6 6 8 8 0 r r t y i p a s I U W ..&.5.7.u.a.k.l.c.c.c.M.M.B.M.V.M.M.c.M.c.c.c.l.a.p.u.7.7.5.3.-.-.+.+.X.X.W Y U s K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . X X X O @ @ @ # # # $ - = > > > , 2 2 2 8 8 8 9 0 r y u u i p s U U ....+.3.7.u.a.k.c.c.c.M.M.M.M.V.B.M.M.M.M.c.c.l.k.a.p.u.7.7.5.3.-.-.&.X.X...W Y I a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . . X . . X X + + @ @ # # # # $ $ - > > > , 2 2 6 6 8 0 0 0 t t u u i s s U U Y X.&.3.7.p.a.a.l.c.c.M.M.M.M.B.V.B.M.M.M.c.c.l.l.a.p.u.7.7.5.3.-.-.&.X.X.X...Y I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                            . . . . . X X X @ + O # # # $ $ > - > > , , 1 2 2 8 8 8 8 r r y y i i p s s U ....&.5.7.u.a.l.l.c.M.c.M.B.V.M.M.M.M.M.c.c.c.l.l.a.p.u.u.7.5.3.-.-.&.X.X...W Y C K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.o                             . . . . O X + + @ + @ # # $ # $ - > > , 1 2 2 2 8 8 8 0 0 t t u u p p a U U ....+.3.7.u.a.l.l.c.c.M.M.M.B.M.V.M.M.M.c.c.c.l.a.p.p.u.7.7.5.3.-.-.&.X.X.X.Y U Y I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.0 +                         . . . . . . o @ + @ + @ # # # $ - $ > > , 1 1 2 2 6 8 8 9 0 t t u i i s a s U ..o.+.5.7.u.a.l.l.c.c.c.M.M.M.B.M.M.M.M.M.c.c.l.l.a.p.u.7.7.5.3.-.-.&.X.X.Y W ....U K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.9 y r #                         . . . . X X X + @ @ @ @ @ # = = > > > < , 2 2 2 2 8 9 9 r r y y u p p s I U ....+.5.7.p.a.a.l.c.c.c.V.M.M.V.M.V.M.M.M.c.c.l.l.a.p.u.7.7.7.3.3.3.+...R X.+.O.X.W K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.8 y y u , .                     . . . . X X X + + @ @ @ $ $ # $ $ = > < , 1 2 8 8 8 9 9 r t t y i i a s I U Y o.+.5.6.u.p.l.c.c.c.c.M.M.V.M.V.M.M.M.c.c.c.l.l.a.p.u.u.5.5.3.-.*.N Q -.-.&.O.O.U K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.6 y u u u t #                 . . . . . X O X + @ + @ @ # # = $ > = > < 1 1 2 2 8 8 8 9 r t t u u i p s I U ....O.5.7.u.p.a.l.c.V.c.V.M.V.V.B.M.M.M.c.c.c.l.l.a.p.u.7.7.3.! v v *.-.3.-.-.&.O.s K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.$ u u u u u i 8 o             . . . . . X X X + @ @ @ @ # $ # $ $ > > > , 1 2 2 2 8 9 8 r t y y i i a s I U U o.+.5.7.p.a.a.l.c.c.c.V.M.M.V.M.M.M.M.M.c.c.l.l.a.u.u.2.Z w 9 Q -.-.-.-.-.-.-. .p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.. 9 u u i i i i u < . .         . . . . X O X X @ @ @ # # # = $ > > > < 1 1 6 2 8 8 8 0 0 t t u u p p s I U ....+.5.7.u.a.l.l.c.M.c.M.B.B.M.V.M.M.M.M.c.c.l.i.,.J e 1 w A -.-.-.-.-.-.-.-.%.I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.. O u u i i i i i i y > .       . . . . . O O + + @ @ # # # # $ $ > > < 1 1 2 2 8 8 8 0 0 t t u u p p s s U Y o.+.5.6.u.a.l.l.c.c.c.M.M.M.M.B.M.M.M.x.t.` n q 2 2 x Q =.-.-.-.-.-.3.-.-.&.W I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K..   # y i i i i i a a a i 8 # .     . . . . + + + @ @ @ # = # $ > > > > , 1 2 2 8 8 9 8 0 r t y u i p s I U Y ..+.3.7.u.p.l.l.c.c.M.M.M.M.x.f.8.H c 2 2 1 6 x K 2.5.5.3.-.-.-.-.3.-.-.+.W Y I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.      + t i i p a a i a a a a u 9 $ . .       . X X + # # # $ $ $ > > < 1 1 2 2 8 8 8 0 0 r t u u p p s I U Y X.O.3.7.u.a.k.k.t.9.' H S h 7 1 > > 1 q M ~ 2.u.7.5.5.5.3.-.-.3.-.3.&.+.....Y I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K..       . , u p p p a a a C C I I U I u 9 = + .       . . . + + @ @ # $ > > 1 1 2 6 8 8 9 0 0 r y u u i i p i p i b v j q 2 < > = > > = 1 5 h D | y.p.p.u.7.7.7.7.5.7.5.5.-.-.-.&.+.X.....Y I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.          O 6 i a a a a C I I U U Y W W o.W T V j 4 & o . . . o . . o o o + O O + @ @ @ # @ # $ # # # # # $ $ # $ # $ - - $ 1 g S ) 8.e.k.k.k.l.p.p.p.u.u.7.7.7.5.5.5.5.-.3.-.+.+.+...W Y I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.            . X 1 u C a I C I U U Y W ..O.O.-.5.7.u.u.i.e.8._ ^ z k d d * * * & % & * & * * * ; - : : : f f k z F ( [ q.h.m.B.B.B.M.M.c.c.l.l.k.k.k.p.p.u.u.u.7.7.5.7.5.3.-.-.&.+.X...W Y I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                  . $ 9 a I U Y Y W W ..O.&.3.5.u.u.p.k.l.l.x.M.M.V.B.C.D.N.N.n.b.n.Z.Z.Z.Z.Z.Z.Z.Z.F.F.G.G.G.G.G.G.D.D.D.C.C.V.M.M.M.c.c.c.l.l.l.a.p.p.p.u.u.u.u.7.7.5.3.-.-.+.O.X...W Y I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                        . # 8 i U W ..X.+.-.5.7.u.p.a.k.l.c.c.M.M.V.C.C.D.D.D.G.G.H.H.H.J.J.J.J.J.J.H.H.H.G.G.G.G.D.D.D.C.D.C.V.M.V.M.c.c.c.l.l.l.l.a.l.a.k.k.p.u.7.5.5.5.3.-.+.+.X...W Y I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . @ , r a E 3.7.7.u.a.a.k.l.c.c.M.M.V.C.D.D.D.D.G.G.H.H.H.J.J.J.J.J.H.H.H.H.H.G.G.G.D.D.D.D.D.C.C.B.M.M.M.c.M.M.M.M.M.c.c.l.l.a.p.u.7.7.5.3.-.-.&.+.X...W Y I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . . . . O @ $ 7 c J | 0.k.l.c.M.M.V.V.C.D.D.D.D.G.G.G.H.H.J.H.J.J.J.H.H.J.J.G.G.G.G.G.G.D.D.C.D.V.C.B.V.V.C.V.M.M.M.c.c.c.l.l.a.p.u.7.7.5.3.-.-.+.O.X.X.W Y I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . . . . . . O + @ + @ # < 7 h S H ` 8.w.f.z.m.N.D.D.D.G.G.H.G.H.G.H.G.D.D.D.C.M.M.c.c.c.c.c.c.c.M.M.M.M.M.B.M.M.M.M.M.c.c.l.l.a.u.p.7.5.5.3.-.-.&.O.X...W Y I a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . . . . . X X X + @ @ @ # # # $ = = < , 2 7 7 q w e x x v b N N N B A I R Y E o.+.-.7.u.a.l.l.c.c.M.M.M.V.V.M.M.M.M.M.c.c.l.l.a.p.u.7.5.5.5.3.-.+.+.X...W Y I i K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . o X + X + + @ # @ $ $ $ = = 1 = 1 , 2 2 6 8 9 9 0 r t y u i a B I I Y ..O.-.7.u.a.l.l.c.c.c.M.M.M.B.V.M.M.M.c.c.c.l.l.a.p.u.7.7.5.3.-.-.&.+.X...W Y I i K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . . . . . X X @ + @ @ # # # $ $ = = = = , , 2 2 6 8 8 9 0 r y y i i p B I I W ..X.-.7.u.p.a.l.c.c.c.M.M.M.B.M.M.M.M.c.c.c.l.l.a.p.u.u.7.5.3.-.-.+.X.X.X.W Y I a K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . . . . o X X X + @ + @ # $ # $ = = = , , , 2 2 6 6 9 9 0 r t y u i a p I U Y ..o.-.7.u.p.l.l.c.c.M.M.M.B.V.M.B.M.M.M.c.c.l.l.a.u.u.7.5.5.3.-.-.&.X.X...W U I i K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . . . . . X X X + @ + # # # $ = = = = = 1 1 2 2 8 6 8 9 0 r t y u i B a I U Y ..X.3.6.u.a.a.l.c.c.c.V.M.M.V.V.M.M.M.M.c.c.l.l.a.p.u.7.7.5.3.3.-.+.+.X...W U I i K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . X X X @ + + @ # # # $ * = = < , 1 1 2 2 6 8 8 8 0 r r y u i p p I I W ..O.-.7.u.p.a.l.c.c.c.V.M.M.B.M.B.M.M.c.c.c.l.k.a.p.u.7.7.5.3.-.-.+.+.X...W Y I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . o X X X + + + @ @ # $ = = = < = 1 1 2 2 6 8 9 9 0 r y y u i p a I I Y ..O.3.7.p.p.l.l.c.c.c.M.M.B.B.M.M.M.M.M.c.c.l.k.a.p.u.u.5.5.3.-.-.&.O.X...W Y I i K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                            . . . . . o X X X + + # # # # $ # = = = 1 , , 2 2 6 6 8 8 0 0 t y u i p B I U Y ..O.-.7.u.p.a.l.c.c.c.M.M.V.M.B.M.M.M.c.c.c.c.l.a.p.u.7.7.5.3.3.-.O.O.o...W U I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . X + X X + @ @ # # # $ * = = = > , , 2 2 6 8 8 9 0 0 t y i i a a I I Y ..O.-.7.u.p.l.l.c.c.M.M.M.V.M.V.B.M.M.c.c.c.l.l.a.p.u.7.5.5.5.3.-.+.+.X...W Y I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . X X X + + + # # # # $ = = < > , 1 2 2 6 8 8 9 9 r y y u i i a C U Y W O.-.6.p.p.l.l.c.c.c.M.M.M.V.M.M.M.M.M.c.c.l.l.a.u.u.7.7.5.3.-.-.+.+.X...W Y I p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . o X X @ + @ @ # # = $ = = = < < 1 2 2 6 6 8 9 0 0 y y u i a a C I Y W O.-.7.u.p.a.l.c.c.c.c.M.M.M.B.B.M.M.c.c.c.l.l.p.p.u.u.7.5.3.-.3.+.+.X...W Y C p K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . . . . X X X X + @ + # @ # # $ = = > < < 1 2 2 6 6 9 9 0 0 r y u i N a I U Y ..O.&.7.u.p.a.l.c.c.M.M.M.V.M.V.M.M.M.M.c.c.l.l.a.p.u.7.7.5.3.-.3.+.X.X...W Y C K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                                . . . . X X X @ @ X # @ # = $ = = > > < 1 2 2 6 6 9 9 0 r t y u i p a C U Y ..O.-.7.u.p.l.l.c.c.c.M.M.M.V.M.M.M.M.c.c.c.l.l.a.p.u.7.7.5.-.-.-.+.+.X.W W Y I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . . . X X X X + + + @ # # # $ $ $ > < 1 1 1 2 6 6 9 9 0 r t y u i p a C U Y W O.-.7.u.a.a.l.c.c.M.M.M.B.B.V.B.M.M.M.c.c.l.k.a.u.u.7.7.5.3.-.3.+.X.o.o.W Y K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                              . X X . X X X @ + # @ # # = $ = = > > < 1 2 2 6 6 8 8 0 0 r y u i p a I I W ..X.-.7.u.p.a.l.l.c.c.M.M.M.M.V.M.M.M.c.c.c.c.l.a.p.u.7.5.5.3.-.-.+.+.X...W C K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                            . . . . X X X + + + # # # # $ $ = > > < 1 2 2 6 6 8 9 0 0 t y u i p a C I Y ..X.-.7.u.p.l.l.c.c.M.M.M.B.V.M.M.M.M.M.c.c.l.k.a.p.u.7.7.5.3.3.-.+.+.X.W Y K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                          . X . . O O O O @ @ @ # # $ $ - - > > < 1 1 2 2 8 8 8 0 r r y u i p a C U Y W O.-.7.u.p.a.l.l.c.M.M.M.M.M.V.M.M.M.M.c.c.l.l.a.p.p.7.6.5.3.-.-.&.+.X.I K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                        . .   X . O . @ @ O # @ # # $ - - > > < 1 2 2 2 8 8 9 0 r t y u i a a C I Y W O.&.7.u.p.a.l.c.c.c.M.M.M.B.V.V.M.M.c.c.c.l.l.a.p.u.7.7.5.-.-.-.+...K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                        . . . O O O O + @ @ # # # $ $ - > > , 1 2 6 6 8 8 9 0 r t y u u p a C I Y ..+.&.7.u.p.l.l.c.c.c.M.M.M.B.M.M.M.M.M.c.c.l.l.a.p.u.7.7.5.-.-.&.E K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                    . o X . o O O O @ + # # # $ $ - - - > < , 1 2 2 8 8 8 9 0 r y u i p a C U Y W +.-.5.u.p.a.l.c.c.M.c.M.B.M.V.B.M.M.c.c.c.l.l.a.u.u.7.7.5.-.@.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.                o     X o O . + + @ @ # # # $ - $ > > , , 2 2 6 8 8 9 0 0 y y u i p p I U Y ..O.-.5.u.p.a.l.c.c.c.M.M.M.M.V.M.M.M.M.c.c.l.l.a.u.u.7.5.#.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.              X X   o O O + @ + @ # # $ # - - > > , , 2 6 2 6 8 9 9 0 r y u u p p I I Y W +.&.7.u.p.a.l.c.c.M.M.M.B.V.M.B.M.M.c.c.c.l.l.a.p.6.#.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.        . .   o   O O X @ @ @ # # $ $ - $ > > , , 2 2 2 6 8 8 0 0 t y u u p a C U Y ..O.&.7.u.p.a.l.l.c.c.M.M.B.M.B.M.M.M.M.c.c.k.i.,.~ K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.    . . . o O O O + + # @ # # $ $ - - > , 1 2 2 6 8 8 9 0 r r y u i p p I I Y W X.-.5.u.p.l.l.c.c.M.M.M.V.B.M.V.M.M.c.k.9.` K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.. . o o o + @ + @ # # $ # - - > > < , 1 6 6 8 8 8 9 r t y u i p p s I Y W X.-.5.u.p.k.l.c.c.c.M.M.M.M.M.j.9.9.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.. O + + @ # # # $ $ $ > > < , 2 2 2 8 8 9 9 r r y u i p a s U U W X.&.5.u.p.l.l.c.x.c.j.w.8.` K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.@ @ @ $ $ - > < 1 2 2 2 8 8 9 9 0 r t u i i a s I E W ..%.1.1.;.;.>.` K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.> < > , 1 1 6 8 8 8 9 0 y r y u K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K."
};