#include "UITreeIcon.h"
const char* ICON_TAG_PARENT[] = {
	"11 11 2 1",
	"o c #121212",
	"a c #EE0000",
	"oooooaooooo",
	"oooooaooooo",
	"oooooaooooo",
	"oooooaooooo",
	"oooooaooooo",
	"aaaaaaaaaaa",
	"oooooaooooo",
	"oooooaooooo",
	"oooooaooooo",
	"oooooaooooo",
	"oooooaooooo"};
const char* ICON_TAG_CHILD[] = {
	"11 11 2 1",
	"o c #121212",
	"a c #98FB98",
	"aoooooooooa",
	"oaoooooooao",
	"ooaoooooaoo",
	"oooaoooaooo",
	"ooooaoaoooo",
	"oooooaooooo",
	"ooooaoaoooo",
	"oooaoooaooo",
	"ooaoooooaoo",
	"oaoooooooao",
	"aoooooooooa"};
const char* ICON_TAG_SELECTED[] = {
	"11 11 3 1",
	"o c #9B30FF",
	"a c #98FB98",
	"b c #00FFFF",
	"bbbbbbbbbbb",
	"aaoooboooaa",
	"aoaoobooaoa",
	"aooaoboaooa",
	"aoooabaoooa",
	"bbbbbabbbbb",
	"aoooabaoooa",
	"aooaoboaooa",
	"aoaoobooaoa",
	"aaoooboooaa",
	"bbbbbbbbbbb"};
extern const char* ICON_TAG_OPEN_PIXMAP[] = {
	"11 11 2 1",
	".  c None",
	"@  c #000000",
	"...@.......",
	"...@@......",
	"...@@@.....",
	"...@@@@....",
	"...@@@@@...",
	"...@@@@@@..",
	"...@@@@@...",
	"...@@@@....",
	"...@@@.....",
	"...@@......",
	"...@......."};
extern const char* ICON_TAG_CLOSE_PIXMAP[] = {
	"11 11 2 1",
	".  c None",
	"@  c #000000",
	"...........",
	"...........",
	"...........",
	"...........",
	"...........",
	"@@@@@@@@@@@",
	".@@@@@@@@@.",
	"..@@@@@@@..",
	"...@@@@@...",
	"....@@@....",
	".....@....."};